
package de.mosbach.lan.smarthome.smarthomecontrolservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2016-03-24T09:24:17.911+01:00
 * Generated source version: 2.7.0
 * 
 */
public final class SmarthomeControlService_SmarthomeControlService_Client {

    private static final QName SERVICE_NAME = new QName("http://smarthomeControlService.smarthome.lan.mosbach.de/", "smarthomeControlService");

    private SmarthomeControlService_SmarthomeControlService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SmarthomeControlService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SmarthomeControlService_Service ss = new SmarthomeControlService_Service(wsdlURL, SERVICE_NAME);
        SmarthomeControlService port = ss.getSmarthomeControlService();  
        
        {
        System.out.println("Invoking turnOnHeater...");
        java.lang.String _turnOnHeater_arg0 = "";
        java.util.List<java.lang.Integer> _turnOnHeater__return = port.turnOnHeater(_turnOnHeater_arg0);
        System.out.println("turnOnHeater.result=" + _turnOnHeater__return);


        }
        {
        System.out.println("Invoking openWindows...");
        java.lang.String _openWindows_arg0 = "";
        java.util.List<java.lang.Integer> _openWindows__return = port.openWindows(_openWindows_arg0);
        System.out.println("openWindows.result=" + _openWindows__return);


        }
        {
        System.out.println("Invoking turnOnAirConditioner...");
        java.lang.String _turnOnAirConditioner_arg0 = "";
        java.util.List<java.lang.Integer> _turnOnAirConditioner__return = port.turnOnAirConditioner(_turnOnAirConditioner_arg0);
        System.out.println("turnOnAirConditioner.result=" + _turnOnAirConditioner__return);


        }
        {
        System.out.println("Invoking shutdownAll...");
        java.lang.String _shutdownAll_arg0 = "";
        java.util.List<java.lang.Integer> _shutdownAll__return = port.shutdownAll(_shutdownAll_arg0);
        System.out.println("shutdownAll.result=" + _shutdownAll__return);


        }

        System.exit(0);
    }

}
