package de.mosbach.lan.smarthome.smarthomecontrolservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2016-03-23T18:42:28.714+01:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://smarthomeControlService.smarthome.lan.mosbach.de/", name = "smarthomeControlService")
@XmlSeeAlso({ObjectFactory.class})
public interface SmarthomeControlService {

    @WebMethod
    @RequestWrapper(localName = "turnOnHeater", targetNamespace = "http://smarthomeControlService.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.smarthomecontrolservice.TurnOnHeater")
    @ResponseWrapper(localName = "turnOnHeaterResponse", targetNamespace = "http://smarthomeControlService.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.smarthomecontrolservice.TurnOnHeaterResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Integer> turnOnHeater(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "openWindows", targetNamespace = "http://smarthomeControlService.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.smarthomecontrolservice.OpenWindows")
    @ResponseWrapper(localName = "openWindowsResponse", targetNamespace = "http://smarthomeControlService.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.smarthomecontrolservice.OpenWindowsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Integer> openWindows(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "turnOnAirConditioner", targetNamespace = "http://smarthomeControlService.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.smarthomecontrolservice.TurnOnAirConditioner")
    @ResponseWrapper(localName = "turnOnAirConditionerResponse", targetNamespace = "http://smarthomeControlService.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.smarthomecontrolservice.TurnOnAirConditionerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Integer> turnOnAirConditioner(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "shutdownAll", targetNamespace = "http://smarthomeControlService.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.smarthomecontrolservice.ShutdownAll")
    @ResponseWrapper(localName = "shutdownAllResponse", targetNamespace = "http://smarthomeControlService.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.smarthomecontrolservice.ShutdownAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Integer> shutdownAll(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
